language: java
jdk: oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a71f75638356_key -iv $encrypted_a71f75638356_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod +x mvnw
- chmod 600 ~/.ssh/id_rsa
- mysql -u root -e 'CREATE DATABASE testbase;'
addons:
  ssh_known_hosts: 101.132.38.91
after_success:
  - ssh root@101.132.38.91 "./do.sh"

