spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ipnet?characterEncoding=UTF-8&useSSL=true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true